version: "3"
services:
    nginx:
      image: yrameshrao/roshani-nginx:latest
      depends_on:
        - litil
        - postgres
      ports:
        - "80:80"
      networks:
        - root  

    litil:
      image: roshnkmri/roshani-litil
      networks:
        - root 

    area51:
      image: roshnkmri/roshani-area51
      networks:
        - root 
      volumes:
        - /opt/persistent_data/area51-data:/srv/app        

    postgres:
      image: postgres:12
      networks:
        - root 
      restart: always
      volumes:
        - /opt/persistent_data/postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: example

    adminer:
      image: adminer
      restart: always
      networks:
        - root 

networks:
  root:
